# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0007_homepagecarouselitem_description")]

    operations = [
        migrations.AddField(
            model_name="homepagecarouselitem",
            name="button_link",
            field=models.TextField(blank=True),
        )
    ]
