# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 18:34
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [("home", "0012_auto_20170121_1806")]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="tease",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        )
    ]
