# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 09:59
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [("home", "0017_auto_20170209_1246")]

    operations = [
        migrations.AlterField(
            model_name="homepageblocks",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_blocks",
                to="home.ExhibitionPage",
            ),
        )
    ]
