# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailforms", "0003_capitalizeverbose"),
        ("wagtailcore", "0032_add_bulk_delete_page_permission"),
        ("wagtailredirects", "0005_capitalizeverbose"),
        ("home", "0018_auto_20170221_0959"),
    ]

    operations = [
        migrations.RemoveField(model_name="aboutlibrarypage", name="page_ptr"),
        migrations.RemoveField(model_name="aboutlibrarypagecarouselitem", name="image"),
        migrations.RemoveField(
            model_name="aboutlibrarypagecarouselitem", name="link_document"
        ),
        migrations.RemoveField(
            model_name="aboutlibrarypagecarouselitem", name="link_page"
        ),
        migrations.RemoveField(model_name="aboutlibrarypagecarouselitem", name="page"),
        migrations.RemoveField(model_name="aboutmuseumpage", name="page_ptr"),
        migrations.RemoveField(model_name="aboutmuseumpagecarouselitem", name="image"),
        migrations.RemoveField(
            model_name="aboutmuseumpagecarouselitem", name="link_document"
        ),
        migrations.RemoveField(
            model_name="aboutmuseumpagecarouselitem", name="link_page"
        ),
        migrations.RemoveField(model_name="aboutmuseumpagecarouselitem", name="page"),
        migrations.RemoveField(model_name="boardofgovernors", name="page_ptr"),
        migrations.RemoveField(model_name="boardofgovernorscarouselitem", name="image"),
        migrations.RemoveField(
            model_name="boardofgovernorscarouselitem", name="link_document"
        ),
        migrations.RemoveField(
            model_name="boardofgovernorscarouselitem", name="link_page"
        ),
        migrations.RemoveField(model_name="boardofgovernorscarouselitem", name="page"),
        migrations.RemoveField(model_name="bookdonations", name="page_ptr"),
        migrations.RemoveField(model_name="bookdonationscarouselitem", name="image"),
        migrations.RemoveField(
            model_name="bookdonationscarouselitem", name="link_document"
        ),
        migrations.RemoveField(
            model_name="bookdonationscarouselitem", name="link_page"
        ),
        migrations.RemoveField(model_name="bookdonationscarouselitem", name="page"),
        migrations.RemoveField(model_name="personpage", name="feed_image"),
        migrations.RemoveField(model_name="personpage", name="image"),
        migrations.RemoveField(model_name="personpage", name="page_ptr"),
        migrations.RemoveField(model_name="personpagecarouselitem", name="image"),
        migrations.RemoveField(
            model_name="personpagecarouselitem", name="link_document"
        ),
        migrations.RemoveField(model_name="personpagecarouselitem", name="link_page"),
        migrations.RemoveField(model_name="personpagecarouselitem", name="page"),
        migrations.RemoveField(
            model_name="personpagerelatedlink", name="link_document"
        ),
        migrations.RemoveField(model_name="personpagerelatedlink", name="link_page"),
        migrations.RemoveField(model_name="personpagerelatedlink", name="page"),
        migrations.RemoveField(model_name="plannedgiving", name="page_ptr"),
        migrations.RemoveField(model_name="plannedgivingcarouselitem", name="image"),
        migrations.RemoveField(
            model_name="plannedgivingcarouselitem", name="link_document"
        ),
        migrations.RemoveField(
            model_name="plannedgivingcarouselitem", name="link_page"
        ),
        migrations.RemoveField(model_name="plannedgivingcarouselitem", name="page"),
        migrations.RemoveField(model_name="staffdirectory", name="page_ptr"),
        migrations.RemoveField(model_name="staffdirectorycarouselitem", name="image"),
        migrations.RemoveField(
            model_name="staffdirectorycarouselitem", name="link_document"
        ),
        migrations.RemoveField(
            model_name="staffdirectorycarouselitem", name="link_page"
        ),
        migrations.RemoveField(model_name="staffdirectorycarouselitem", name="page"),
        migrations.RemoveField(model_name="supportpage", name="page_ptr"),
        migrations.RemoveField(model_name="supportpagecarouselitem", name="image"),
        migrations.RemoveField(
            model_name="supportpagecarouselitem", name="link_document"
        ),
        migrations.RemoveField(model_name="supportpagecarouselitem", name="link_page"),
        migrations.RemoveField(model_name="supportpagecarouselitem", name="page"),
        migrations.RemoveField(model_name="visitus", name="page_ptr"),
        migrations.RemoveField(model_name="visituscarouselitem", name="image"),
        migrations.RemoveField(model_name="visituscarouselitem", name="link_document"),
        migrations.RemoveField(model_name="visituscarouselitem", name="link_page"),
        migrations.RemoveField(model_name="visituscarouselitem", name="page"),
        migrations.RemoveField(model_name="xggrhistory", name="page_ptr"),
        migrations.RemoveField(model_name="xggrhistorycarouselitem", name="image"),
        migrations.RemoveField(
            model_name="xggrhistorycarouselitem", name="link_document"
        ),
        migrations.RemoveField(model_name="xggrhistorycarouselitem", name="link_page"),
        migrations.RemoveField(model_name="xggrhistorycarouselitem", name="page"),
        migrations.RemoveField(model_name="youthtraining", name="page_ptr"),
        migrations.RemoveField(
            model_name="youthtrainingpagecarouselitem", name="image"
        ),
        migrations.RemoveField(
            model_name="youthtrainingpagecarouselitem", name="link_document"
        ),
        migrations.RemoveField(
            model_name="youthtrainingpagecarouselitem", name="link_page"
        ),
        migrations.RemoveField(model_name="youthtrainingpagecarouselitem", name="page"),
        migrations.DeleteModel(name="AboutLibraryPage"),
        migrations.DeleteModel(name="AboutLibraryPageCarouselItem"),
        migrations.DeleteModel(name="AboutMuseumPage"),
        migrations.DeleteModel(name="AboutMuseumPageCarouselItem"),
        migrations.DeleteModel(name="BoardOfGovernors"),
        migrations.DeleteModel(name="BoardOfGovernorsCarouselItem"),
        migrations.DeleteModel(name="BookDonations"),
        migrations.DeleteModel(name="BookDonationsCarouselItem"),
        migrations.DeleteModel(name="PersonPage"),
        migrations.DeleteModel(name="PersonPageCarouselItem"),
        migrations.DeleteModel(name="PersonPageRelatedLink"),
        migrations.DeleteModel(name="PlannedGiving"),
        migrations.DeleteModel(name="PlannedGivingCarouselItem"),
        migrations.DeleteModel(name="StaffDirectory"),
        migrations.DeleteModel(name="StaffDirectoryCarouselItem"),
        migrations.DeleteModel(name="SupportPage"),
        migrations.DeleteModel(name="SupportPageCarouselItem"),
        migrations.DeleteModel(name="VisitUs"),
        migrations.DeleteModel(name="VisitUsCarouselItem"),
        migrations.DeleteModel(name="XGGRHistory"),
        migrations.DeleteModel(name="XGGRHistoryCarouselItem"),
        migrations.DeleteModel(name="YouthTraining"),
        migrations.DeleteModel(name="YouthTrainingPageCarouselItem"),
    ]
