# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailforms", "0003_capitalizeverbose"),
        ("wagtailcore", "0032_add_bulk_delete_page_permission"),
        ("wagtailredirects", "0005_capitalizeverbose"),
        ("home", "0019_auto_20170303_2347"),
    ]

    operations = [
        migrations.RemoveField(model_name="contactpage", name="feed_image"),
        migrations.RemoveField(model_name="contactpage", name="page_ptr"),
        migrations.RemoveField(model_name="contactpagecarouselitem", name="image"),
        migrations.RemoveField(
            model_name="contactpagecarouselitem", name="link_document"
        ),
        migrations.RemoveField(model_name="contactpagecarouselitem", name="link_page"),
        migrations.RemoveField(model_name="contactpagecarouselitem", name="page"),
        migrations.AddField(
            model_name="contactuspage",
            name="address_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="address_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="country",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="post_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="telephone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(name="ContactPage"),
        migrations.DeleteModel(name="ContactPageCarouselItem"),
    ]
