# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [("home", "0021_contactmessage")]

    operations = [
        migrations.AddField(
            model_name="contactuspage",
            name="from_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="thank_you_text",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="to_address",
            field=models.CharField(
                blank=True,
                help_text="Optional - form submissions will be emailed to this address",
                max_length=255,
            ),
        ),
    ]
