# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailforms", "0003_capitalizeverbose"),
        ("wagtailcore", "0032_add_bulk_delete_page_permission"),
        ("wagtailredirects", "0005_capitalizeverbose"),
        ("wagtailimages", "0017_reduce_focal_point_key_max_length"),
        ("home", "0024_membershippagecarouselitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address_1", models.CharField(blank=True, max_length=255)),
                ("address_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=255)),
                ("post_code", models.CharField(blank=True, max_length=10)),
                ("body", wagtail.wagtailcore.fields.RichTextField(blank=True)),
                (
                    "feed_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.RenameModel(
            old_name="MemberShipPageCarouselItem", new_name="ContactPageCarouselItem"
        ),
        migrations.DeleteModel(name="ContactMessage"),
        migrations.RemoveField(model_name="membershippage", name="page_ptr"),
        migrations.DeleteModel(name="MembershipRequest"),
        migrations.DeleteModel(name="SpaceRequest"),
        migrations.RemoveField(model_name="bookspace", name="from_address"),
        migrations.RemoveField(model_name="bookspace", name="subject"),
        migrations.RemoveField(model_name="bookspace", name="thank_you_text"),
        migrations.RemoveField(model_name="bookspace", name="to_address"),
        migrations.RemoveField(model_name="contactuspage", name="address_1"),
        migrations.RemoveField(model_name="contactuspage", name="address_2"),
        migrations.RemoveField(model_name="contactuspage", name="city"),
        migrations.RemoveField(model_name="contactuspage", name="country"),
        migrations.RemoveField(model_name="contactuspage", name="email"),
        migrations.RemoveField(model_name="contactuspage", name="from_address"),
        migrations.RemoveField(model_name="contactuspage", name="post_code"),
        migrations.RemoveField(model_name="contactuspage", name="subject"),
        migrations.RemoveField(model_name="contactuspage", name="telephone"),
        migrations.RemoveField(model_name="contactuspage", name="thank_you_text"),
        migrations.RemoveField(model_name="contactuspage", name="to_address"),
        migrations.AlterField(
            model_name="contactpagecarouselitem",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carousel_items",
                to="home.ContactPage",
            ),
        ),
        migrations.DeleteModel(name="MemberShipPage"),
    ]
