# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-11 07:53
from __future__ import unicode_literals

from django.db import migrations
import home.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [("home", "0030_auto_20171206_1254")]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="body_pt",
            field=wagtail.wagtailcore.fields.StreamField(
                [
                    (
                        b"h2",
                        wagtail.wagtailcore.blocks.CharBlock(
                            classname="title", icon="title"
                        ),
                    ),
                    (
                        b"h3",
                        wagtail.wagtailcore.blocks.CharBlock(
                            classname="title", icon="title"
                        ),
                    ),
                    (
                        b"h4",
                        wagtail.wagtailcore.blocks.CharBlock(
                            classname="title", icon="title"
                        ),
                    ),
                    (
                        b"intro",
                        wagtail.wagtailcore.blocks.RichTextBlock(icon="pilcrow"),
                    ),
                    (
                        b"paragraph",
                        wagtail.wagtailcore.blocks.RichTextBlock(icon="pilcrow"),
                    ),
                    (
                        b"aligned_image",
                        wagtail.wagtailcore.blocks.StructBlock(
                            [
                                (
                                    b"image",
                                    wagtail.wagtailimages.blocks.ImageChooserBlock(),
                                ),
                                (
                                    b"caption",
                                    wagtail.wagtailcore.blocks.RichTextBlock(),
                                ),
                                (b"alignment", home.models.ImageFormatChoiceBlock()),
                            ],
                            icon="image",
                            label="Aligned image",
                        ),
                    ),
                    (
                        b"pullquote",
                        wagtail.wagtailcore.blocks.StructBlock(
                            [
                                (
                                    b"quote",
                                    wagtail.wagtailcore.blocks.TextBlock("quote title"),
                                ),
                                (
                                    b"attribution",
                                    wagtail.wagtailcore.blocks.CharBlock(),
                                ),
                            ]
                        ),
                    ),
                    (
                        b"aligned_html",
                        wagtail.wagtailcore.blocks.StructBlock(
                            [
                                (b"html", wagtail.wagtailcore.blocks.RawHTMLBlock()),
                                (b"alignment", home.models.HTMLAlignmentChoiceBlock()),
                            ],
                            icon="code",
                            label="Raw HTML",
                        ),
                    ),
                    (
                        b"document",
                        wagtail.wagtaildocs.blocks.DocumentChooserBlock(
                            icon="doc-full-inverse"
                        ),
                    ),
                ],
                default="",
            ),
            preserve_default=False,
        )
    ]
