# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [("home", "0033_auto_20171211_1051")]

    operations = [
        migrations.RenameField(
            model_name="blogindexpage", old_name="intro", new_name="intro_en"
        ),
        migrations.RenameField(
            model_name="contactuspage", old_name="body", new_name="body_en"
        ),
        migrations.RenameField(
            model_name="contactuspage", old_name="intro", new_name="intro_en"
        ),
        migrations.RenameField(
            model_name="contactuspage",
            old_name="thank_you_text",
            new_name="thank_you_text_en",
        ),
        migrations.RenameField(
            model_name="exhibitionpage", old_name="body", new_name="body_en"
        ),
        migrations.RenameField(
            model_name="exhibitionpage", old_name="intro", new_name="intro_en"
        ),
        migrations.RemoveField(model_name="blogpage", name="body_pt"),
        migrations.RemoveField(model_name="blogpage", name="tease_pt"),
        migrations.AddField(
            model_name="blogindexpage",
            name="intro_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="body_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="intro_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="contactuspage",
            name="thank_you_text_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="exhibitionpage",
            name="body_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="exhibitionpage",
            name="intro_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="organisation",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Organisation"
            ),
        ),
        migrations.AlterField(
            model_name="contactuspage",
            name="address_1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Address 1"
            ),
        ),
        migrations.AlterField(
            model_name="contactuspage",
            name="address_2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Address 2"
            ),
        ),
        migrations.AlterField(
            model_name="contactuspage",
            name="city",
            field=models.CharField(blank=True, max_length=255, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="contactuspage",
            name="country",
            field=models.CharField(blank=True, max_length=255, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="contactuspage",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contactuspage",
            name="post_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="Post Code"),
        ),
        migrations.AlterField(
            model_name="contactuspage",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telephone"),
        ),
        migrations.AlterField(
            model_name="exhibitionpage",
            name="cost",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Cost"
            ),
        ),
        migrations.AlterField(
            model_name="membershippage",
            name="address_1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Address 1"
            ),
        ),
        migrations.AlterField(
            model_name="membershippage",
            name="address_2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Address 2"
            ),
        ),
        migrations.AlterField(
            model_name="membershippage",
            name="city",
            field=models.CharField(blank=True, max_length=255, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="membershippage",
            name="country",
            field=models.CharField(blank=True, max_length=255, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="membershippage",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="membershippage",
            name="post_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="Post Code"),
        ),
        migrations.AlterField(
            model_name="membershippage",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telephone"),
        ),
        migrations.AlterField(
            model_name="membershiprequest",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="spacerequest",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="spacerequest",
            name="organisation",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Organisation"
            ),
        ),
    ]
