# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-01 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtaildocs", "0007_merge"),
        ("wagtailcore", "0039_collectionviewrestriction"),
        ("home", "0038_auto_20180122_1034"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExhPageBlocks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "link_external",
                    models.URLField(blank=True, verbose_name="External link"),
                ),
                ("title_en", models.CharField(help_text="Title", max_length=255)),
                (
                    "title_tet",
                    models.CharField(help_text="Title", max_length=255, null=True),
                ),
                ("body_en", wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ("body_tet", wagtail.wagtailcore.fields.RichTextField(blank=True)),
                (
                    "link_title_en",
                    models.CharField(help_text="Link title", max_length=255),
                ),
                (
                    "link_title_tet",
                    models.CharField(help_text="Link title", max_length=255),
                ),
                (
                    "link_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtaildocs.Document",
                    ),
                ),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_blocks",
                        to="home.ExhibitionPage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False},
        ),
        migrations.RenameField(
            model_name="aboutpageblocks", old_name="body", new_name="body_en"
        ),
        migrations.RenameField(
            model_name="aboutpageblocks",
            old_name="link_title",
            new_name="link_title_en",
        ),
        migrations.RenameField(
            model_name="aboutpageblocks", old_name="title", new_name="title_en"
        ),
        migrations.RenameField(
            model_name="aboutpagecarouselitem",
            old_name="button_link",
            new_name="button_link_en",
        ),
        migrations.RenameField(
            model_name="aboutpagecarouselitem",
            old_name="caption",
            new_name="caption_en",
        ),
        migrations.RenameField(
            model_name="aboutpagecarouselitem",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="blogindexpagecarouselitem",
            old_name="button_link",
            new_name="button_link_en",
        ),
        migrations.RenameField(
            model_name="blogindexpagecarouselitem",
            old_name="caption",
            new_name="caption_en",
        ),
        migrations.RenameField(
            model_name="blogindexpagecarouselitem",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="blogindexpagerelatedlink", old_name="title", new_name="title_en"
        ),
        migrations.RenameField(
            model_name="blogpagecarouselitem",
            old_name="button_link",
            new_name="button_link_en",
        ),
        migrations.RenameField(
            model_name="blogpagecarouselitem", old_name="caption", new_name="caption_en"
        ),
        migrations.RenameField(
            model_name="blogpagecarouselitem",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="blogpagerelatedlink", old_name="title", new_name="title_en"
        ),
        migrations.RenameField(
            model_name="bookspacecarouselitem",
            old_name="button_link",
            new_name="button_link_en",
        ),
        migrations.RenameField(
            model_name="bookspacecarouselitem",
            old_name="caption",
            new_name="caption_en",
        ),
        migrations.RenameField(
            model_name="bookspacecarouselitem",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="contactuspagecarouselitem",
            old_name="button_link",
            new_name="button_link_en",
        ),
        migrations.RenameField(
            model_name="contactuspagecarouselitem",
            old_name="caption",
            new_name="caption_en",
        ),
        migrations.RenameField(
            model_name="contactuspagecarouselitem",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="eventindexpagecarouselitem",
            old_name="button_link",
            new_name="button_link_en",
        ),
        migrations.RenameField(
            model_name="eventindexpagecarouselitem",
            old_name="caption",
            new_name="caption_en",
        ),
        migrations.RenameField(
            model_name="eventindexpagecarouselitem",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="eventindexpagerelatedlink",
            old_name="title",
            new_name="title_en",
        ),
        migrations.RenameField(
            model_name="eventpagecarouselitem",
            old_name="button_link",
            new_name="button_link_en",
        ),
        migrations.RenameField(
            model_name="eventpagecarouselitem",
            old_name="caption",
            new_name="caption_en",
        ),
        migrations.RenameField(
            model_name="eventpagecarouselitem",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="eventpagerelatedlink", old_name="title", new_name="title_en"
        ),
        migrations.RenameField(
            model_name="exhibitionpagecarouselitem",
            old_name="button_link",
            new_name="button_link_en",
        ),
        migrations.RenameField(
            model_name="exhibitionpagecarouselitem",
            old_name="caption",
            new_name="caption_en",
        ),
        migrations.RenameField(
            model_name="exhibitionpagecarouselitem",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="homepage", old_name="intro", new_name="intro_en"
        ),
        migrations.RenameField(
            model_name="homepageblocks", old_name="body", new_name="body_en"
        ),
        migrations.RenameField(
            model_name="homepageblocks", old_name="link_title", new_name="link_title_en"
        ),
        migrations.RenameField(
            model_name="homepageblocks", old_name="title", new_name="title_en"
        ),
        migrations.RenameField(
            model_name="homepagecarouselitem",
            old_name="button_link",
            new_name="button_link_en",
        ),
        migrations.RenameField(
            model_name="homepagecarouselitem", old_name="caption", new_name="caption_en"
        ),
        migrations.RenameField(
            model_name="homepagecarouselitem",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="librarypageblocks", old_name="body", new_name="body_en"
        ),
        migrations.RenameField(
            model_name="librarypageblocks",
            old_name="link_title",
            new_name="link_title_en",
        ),
        migrations.RenameField(
            model_name="librarypageblocks", old_name="title", new_name="title_en"
        ),
        migrations.RenameField(
            model_name="librarypagecarouselitem",
            old_name="button_link",
            new_name="button_link_en",
        ),
        migrations.RenameField(
            model_name="librarypagecarouselitem",
            old_name="caption",
            new_name="caption_en",
        ),
        migrations.RenameField(
            model_name="librarypagecarouselitem",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="membershippagecarouselitem",
            old_name="button_link",
            new_name="button_link_en",
        ),
        migrations.RenameField(
            model_name="membershippagecarouselitem",
            old_name="caption",
            new_name="caption_en",
        ),
        migrations.RenameField(
            model_name="membershippagecarouselitem",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="museumpage", old_name="body", new_name="body_en"
        ),
        migrations.RenameField(
            model_name="museumpage", old_name="intro", new_name="intro_en"
        ),
        migrations.RenameField(
            model_name="museumpageblocks", old_name="body", new_name="body_en"
        ),
        migrations.RenameField(
            model_name="museumpageblocks",
            old_name="link_title",
            new_name="link_title_en",
        ),
        migrations.RenameField(
            model_name="museumpageblocks", old_name="title", new_name="title_en"
        ),
        migrations.RenameField(
            model_name="museumpagecarouselitem",
            old_name="button_link",
            new_name="button_link_en",
        ),
        migrations.RenameField(
            model_name="museumpagecarouselitem",
            old_name="caption",
            new_name="caption_en",
        ),
        migrations.RenameField(
            model_name="museumpagecarouselitem",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="permanentexhibitionpagecarouselitem",
            old_name="button_link",
            new_name="button_link_en",
        ),
        migrations.RenameField(
            model_name="permanentexhibitionpagecarouselitem",
            old_name="caption",
            new_name="caption_en",
        ),
        migrations.RenameField(
            model_name="permanentexhibitionpagecarouselitem",
            old_name="description",
            new_name="description_en",
        ),
        migrations.RenameField(
            model_name="permexhibpageblocks", old_name="body", new_name="body_en"
        ),
        migrations.RenameField(
            model_name="permexhibpageblocks",
            old_name="link_title",
            new_name="link_title_en",
        ),
        migrations.RenameField(
            model_name="permexhibpageblocks", old_name="title", new_name="title_en"
        ),
        migrations.RenameField(
            model_name="tempexhibpageblocks", old_name="body", new_name="body_en"
        ),
        migrations.RenameField(
            model_name="tempexhibpageblocks",
            old_name="link_title",
            new_name="link_title_en",
        ),
        migrations.RenameField(
            model_name="tempexhibpageblocks", old_name="title", new_name="title_en"
        ),
        migrations.RenameField(
            model_name="temporaryexhibitionpagecarouselitem",
            old_name="button_link",
            new_name="button_link_en",
        ),
        migrations.RenameField(
            model_name="temporaryexhibitionpagecarouselitem",
            old_name="caption",
            new_name="caption_en",
        ),
        migrations.RenameField(
            model_name="temporaryexhibitionpagecarouselitem",
            old_name="description",
            new_name="description_en",
        ),
        migrations.AddField(
            model_name="aboutpageblocks",
            name="body_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="aboutpageblocks",
            name="link_title_tet",
            field=models.CharField(default="", help_text="Link title", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aboutpageblocks",
            name="title_tet",
            field=models.CharField(help_text="Title", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aboutpagecarouselitem",
            name="button_link_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutpagecarouselitem",
            name="caption_tet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aboutpagecarouselitem",
            name="description_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogindexpagecarouselitem",
            name="button_link_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogindexpagecarouselitem",
            name="caption_tet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blogindexpagecarouselitem",
            name="description_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogindexpagerelatedlink",
            name="title_tet",
            field=models.CharField(help_text="Link title", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blogpagecarouselitem",
            name="button_link_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpagecarouselitem",
            name="caption_tet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blogpagecarouselitem",
            name="description_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpagerelatedlink",
            name="title_tet",
            field=models.CharField(help_text="Link title", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bookspacecarouselitem",
            name="button_link_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookspacecarouselitem",
            name="caption_tet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bookspacecarouselitem",
            name="description_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactuspagecarouselitem",
            name="button_link_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactuspagecarouselitem",
            name="caption_tet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contactuspagecarouselitem",
            name="description_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventindexpagecarouselitem",
            name="button_link_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventindexpagecarouselitem",
            name="caption_tet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eventindexpagecarouselitem",
            name="description_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventindexpagerelatedlink",
            name="title_tet",
            field=models.CharField(help_text="Link title", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eventpagecarouselitem",
            name="button_link_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventpagecarouselitem",
            name="caption_tet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eventpagecarouselitem",
            name="description_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventpagerelatedlink",
            name="title_tet",
            field=models.CharField(help_text="Link title", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exhibitionpagecarouselitem",
            name="button_link_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exhibitionpagecarouselitem",
            name="caption_tet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exhibitionpagecarouselitem",
            name="description_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="intro_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepageblocks",
            name="body_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepageblocks",
            name="link_title_tet",
            field=models.CharField(default="", help_text="Link title", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepageblocks",
            name="title_tet",
            field=models.CharField(help_text="Title", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="homepagecarouselitem",
            name="button_link_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepagecarouselitem",
            name="caption_tet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="homepagecarouselitem",
            name="description_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="librarypageblocks",
            name="body_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="librarypageblocks",
            name="link_title_tet",
            field=models.CharField(default="", help_text="Link title", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="librarypageblocks",
            name="title_tet",
            field=models.CharField(help_text="Title", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="librarypagecarouselitem",
            name="button_link_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="librarypagecarouselitem",
            name="caption_tet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="librarypagecarouselitem",
            name="description_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membershippagecarouselitem",
            name="button_link_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membershippagecarouselitem",
            name="caption_tet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="membershippagecarouselitem",
            name="description_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="museumpageblocks",
            name="body_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="museumpageblocks",
            name="link_title_tet",
            field=models.CharField(default="", help_text="Link title", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="museumpageblocks",
            name="title_tet",
            field=models.CharField(help_text="Title", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="museumpagecarouselitem",
            name="button_link_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="museumpagecarouselitem",
            name="caption_tet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="museumpagecarouselitem",
            name="description_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permanentexhibitionpagecarouselitem",
            name="button_link_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permanentexhibitionpagecarouselitem",
            name="caption_tet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="permanentexhibitionpagecarouselitem",
            name="description_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permexhibpageblocks",
            name="body_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="permexhibpageblocks",
            name="link_title_tet",
            field=models.CharField(default="", help_text="Link title", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permexhibpageblocks",
            name="title_tet",
            field=models.CharField(help_text="Title", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tempexhibpageblocks",
            name="body_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="tempexhibpageblocks",
            name="link_title_tet",
            field=models.CharField(default="", help_text="Link title", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tempexhibpageblocks",
            name="title_tet",
            field=models.CharField(help_text="Title", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="temporaryexhibitionpagecarouselitem",
            name="button_link_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="temporaryexhibitionpagecarouselitem",
            name="caption_tet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="temporaryexhibitionpagecarouselitem",
            name="description_tet",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="homepageblocks",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_blocks",
                to="home.HomePage",
            ),
        ),
    ]
