# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-15 19:41
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [("home", "0041_auto_20180415_1927")]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="body_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        )
    ]
