# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-15 19:55
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [("home", "0043_auto_20180415_1953")]

    operations = [
        migrations.RenameField(
            model_name="librarypage", old_name="body", new_name="body_en"
        ),
        migrations.RenameField(
            model_name="librarypage", old_name="intro", new_name="intro_en"
        ),
        migrations.AddField(
            model_name="librarypage",
            name="body_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="librarypage",
            name="intro_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
