# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-23 19:32
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [("home", "0046_auto_20180420_1443")]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="title_en",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="title_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.RenameField(
            model_name="aboutpage", old_name="body_tet", new_name="intro"
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="body_tet",
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
